### ISSUE TITLE
Eastern Hemisphere Meeting - Saturday, 7th August 2021 - 6:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#19]
### Eastern Hemisphere Meeting - Saturday, 7th August 2021 - 6:00 UTC
- Last Meeting - https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/16
- Next Meeting - 

![C3ETH Webpage Banner Mockup](https://user-images.githubusercontent.com/82072426/128649742-47dc031d-b14a-4bb1-92f5-b425f1bb5a54.png)

### Attendees

- Yan Yirta ( @YanTirta )
- Ngọc My Trần Lê - VN - Vietnam
- Robert O'Brien ( @wolstaeb )
- Felix Weber (@FelixfromSwarm )

### Documentation

- Robert O'Brien

### Overview of Discussion

1. Answering Questions in Breakout Rooms ( @YanTirta )
2. Fund 6 Challenge Proposals ( @wolstaeb )
3. Fund 6 C3ETH Proposal Structure ( @wolstaeb )
4. Translation and Git/Markedown ( @wolstaeb )
5. Instagram 9-Steps Posters ( @YanTirta )
6. Website Design and translation. ( @wolstaeb )
7. Website video mockup ( @wolstaeb @PardusEidolon )

#### Answering Questions in Breakout Rooms

@YanTirta raised an issue about answering questions in the breakout room. He attempts to answer questions but people in the rooms may be more knowledgeable about Cardano. They are Stake Pool operators and as a moderator, he didn't know as much about the topic being raised.

Reflecting on the English room, @wolstaeb had these comments.

1. Greg kept the discussion focused mostly on Q&A for Catalyst.
2. We asked for self-introductions and noted interests;
3. That enables the moderators to direct questions and prompt for reflections from them later.
4. If anything, Greg/Robert answered too many of the questions in the English break-out room because we could;
5. Better to try and facilitate a group conversation and get everyone involved;
6. It will get easy as we get to know people, and people feel more comfortable.

One suggestion is that room moderators can/should invite others into their room to answer questions. The request can be put in sessions chat and @wolstaeb Greg etc, could jump in. Where a moderator could do the needed interpretation.

**NOTE**: In Discord, Tim O'Brien has suggested also doing a FAQ that would help with answering questions.

> Does anyone else think it be a good idea to collect questions we receive in our town hall session into a spreadsheet- also include our own? These questions and answers could be added shared with the Catalyst School, to possibly be included in their FAQ, as well be used by translators and moderators as a refresher before meetings.

- [ ] Need to check the chat remains open to everyone across all the rooms. ( @FelixfromSwarm )

#### Fund 6 Community Challenge Setting

Dor has suggested C3ETH group put up some language/country-specific community challenges. 

> Preparing dedicated native language challenges - e.g. A challenge made completely in your native language, that can be reviewed by native CA's etc' Can be multiple challenges that get created by distinct groups such as Japanese, Korean, Vietnamese etc' - I think having something like that would prepare solid foundations for greater inclusion. 

![Project Catalyst Challenge Setting Workshop](https://user-images.githubusercontent.com/82072426/128650933-61dcd4af-72e4-4eed-85cb-b1824d157d9d.png)

Dor also provided links earlier to a Challenge setting [workshop notes](https://docs.google.com/presentation/d/1KGiwqfx7F7oV1gAPbfM6E5Xtzi-4nKAqeaORp7iNUsk/edit#slide=id.gba55c11b28_0_0) and the [recording of the workshop](https://youtu.be/po4ufj2DiRc?t=5691). 

The aim is that the challenge, the proposals, the review process, and the voting, are all done in the native language of the country. To do this would require developing a full pipeline and on-boarding for Catalyst:

1. Development of the challenge specific to local interests/language of the country.
2. Helping onboard potential proposers and teams.
3. Mentoring the proposers.
4. Onboarding and helping Community Advisors that are able to review proposals.
5. Finding 2-3 Veteran CAs for the final assessment.

This is rather a large undertaking, so we'll have to consider which language/countries to do first. There is also a matter of compensation for effort/time that may fall into one of the Fund 6 C3ETH Proposals.

@FelixfromSwarm suggested as a way to onboard and start the proposal funnel is to use the Catalyst Swarm Hackathon and the Mini-proposals. See issue #18 notes.

#### Fund 6 C3ETH Proposal(s)

The C3ETH proposal(s) should be structure into two parts: 

1. An overriding theme (the Vision/Mission of the C3ETH).
2. Challenge/Proposal Specific parts.

The intention is these proposals help fund the effort to build the community and compensate for doing the work required on projects like developing a native language Community Challenge proposal and proposal funnel. As Greg has suggested these proposals will be half retroactive funding (funding for past effort), and proactive funding.

These proposals will be fully translated into as many C3ETH languages as possible and the proposal structure and artefacts will support doing that. Video will also play an important role in communicating the goals of C3ETH and the proposals.

- [ ] Need to developing team skills in doing translation pipeline using GitHub and markdown. ( @everyone )
- [ ] Team members need to set up a GitHub account and let @wolstaeb know. ( @everyone )
 
#### Translation

The C3ETH is made up of lots of languages and cultures. In order to reflect that, and be as inclusive as possible, it is very important to do language translations. 

To make this tractable for our community we will be using Git/Github/Gitbook and [Markdown](https://guides.github.com/features/mastering-markdown/). For more advanced documentation @wolstaeb prefers [asciidoc](https://asciidoctor.org/docs/what-is-asciidoc/). Along with tools such as the website static site generator [hugo](https://gohugo.io/) to make it as easy and consistent as possible.

To help develop team skills using these tools:

1. We do a simple translation exercise first. @wolstaeb suggested we do the landing page video first (see below).
2. @YanTirta is already working on translating the Catalyst Guide so this can work on next.
3. Then we can work on Fund 6 proposal.

@wolstaeb demonstrated markdown and how it can be used to update the published C3ETH website (when it is up.).

**NOTE**: Tim O'Brien's suggestion of an FAQ would also be a good exercise in helping the team do translations.

- [ ] Set up a repository for media assets and there translation starting with the landing page video ( @wolstaeb )
- [ ] Do mini-workshops with team members to help them navigate and use Github and markdown translations. ( @wolstaeb )
- [ ] Learn [Markdown](https://guides.github.com/features/mastering-markdown/) ( @everyone )

#### Instagram Nine Steps

@YanTirta brought up his aim of developing social media posters - nine steps to project catalysts. The aim is to use these social media assets to promote both Catalyst and C3ETH. @YanTirta asked if these would be useful for helping with translation exercises. @wolstaeb agreed and suggested doing the text of these posters first, then branding. Putting the text up into GitHub and work on the translations.

-[] Set up an Instagram folder in the media-asset repo, and help @YanTirta with the initial text/setup (@wolstaeb )

#### Website and Landing Page.

@wolstaeb discussed a draft landing page design/poster Tim had sent (as per discussion in #15 ) that was based around the original C3ETH presentation design @FelixfromSwarm had done.

![Presentation Style](https://user-images.githubusercontent.com/82072426/128652153-1a216259-b169-4971-8496-415702832d53.png)
 
![image_2021_08_03T10_45_07_507Z (1)](https://user-images.githubusercontent.com/82072426/128652134-9a2360d4-0385-4d33-baf3-45bb1009d643.png)

Two issues with the approach were raised by @wolstaeb:

1. A little involved to get this done as a landing page, so better to just use a blog template as a starting point.
2. On reflection, the design we've been using wasn't that inviting. It is too corporate. This was in reference to the points Greg raised in #15 that we don't want to be too slick because that will turn people away. 

Just prior to the meeting @wolstaeb did a mockup of a website design using some collecting images from prior meetings. The idea was to explore a more fun/friendly design while avoiding being too slick. This was presented to the team present, and they liked the approach and agreed with moving ahead in that direction and refining it.

![Website mockup](https://user-images.githubusercontent.com/82072426/128652550-5d81064e-d955-49b1-93f2-ea5f88ace894.png)

- @wolstaeb will implement the site using [Hugo](https://gohugo.io/) and the content will be written in Markdown.
- Hugo easily supports multiple languages.
- Content to the site can be updated via Github, and using Github's [action workflows](https://docs.github.com/en/actions) will be automatically republished with the new content.

@YanTirta asked how others can help, and @wolstaeb suggested working on the content of the site.

- [ ] Get initial site design and template configured with multi-language support ( @wolstaeb )
- [ ] Work on site (home page) content ( lead by @YanTirta )
- [ ] Translate home page content ( @everyone coordinated by @YanTirta  )

#### Website Video Mockup.

Continuing on the Website work, @wolstaeb asked @PardusEidolon to quickly create a mockup video suitable for the website's home page. The work would also lead to developing banner videos discussed in #15. The draft [video was presented](https://www.youtube.com/watch?v=iCXHLehQjaY) to the team.

![Video mockup](https://user-images.githubusercontent.com/82072426/128653072-e3eae987-4352-43d2-baca-5e6e558c1e7b.png)

People liked the direction so it was agreed to refine the video. Since the video used what sources we had available we will need to take action to collect better source content (peoples zoom video) from an upcoming meeting. This will require peoples consent. 

We also discussed creating (rendering) multiple videos for each language. These would be presented on the respective language home page. To do that we will need translations. Since the amount of translating need is small, there was seen as a good exercise to get team members use to using Git/Github and markdown for translations. 

- [ ] Refine the video timeline and content structure ( @PardusEidolon and @wolstaeb ).
- [ ] Set up a folder in the media-assets repo for translation ( @wolstaeb )
- [ ] Coordinate some mini-workshops to help team members to do the translation (@FelixfromSwarm @YanTirta Mie)

**Comment by YanTirta** [comment]
Awesome work Robert!

Don't know how you manage to get this amount of details since you were also
a moderator. Please kindly find notes from my side through this following
link :
https://docs.google.com/document/d/1AeQIo6SQjnfri67fjrBX8iQ3aywWNDneGYKw6zSkijg/edit#

Since the format you have developed is different from what I am used to.
How would you reckon the method of me adding points to it. Would I just
edit directly or would you prefer I provide my documentations as above and
for you to edit the documents?

There are points that I forgot to remind everyone are :
1. The time line
2. Next meeting topics
3. An agreed consistent timing for; Review Meeting after ETH and Prep
Meeting prior ETH (for efficiency could be one meeting)

Would really appreciate everyone's input. Will also share this onto our
Discord channel also.

Awesome regards,
Yan

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by YanTirta** [comment]
@wolstaeb , would it be possible to share the raw files of the template you designed for the landing page? I would like to use the semi-transparent geometric shapes you overlay on top of the Zoom profiles collage. My intent is to continue that style for the 9 Instagram steps first iteration.

**Comment by wolstaeb** [comment]
You should have permission to just edit the content. So please go ahead and update it with additional details.  If you'd prefer that I do it just say.

> Since the format you have developed is different from what I am used to. How would you reckon the method of me adding points to it.

**Comment by stephen-rowan** [comment]
Great notes @wolstaeb - a pleasure to see !

**Comment by YanTirta** [comment]
@wolstaeb , kindly find the translated document that we previously talked about. With a short reminder, _"we agreed to have a tab on the landing page that translates on **how to propose a proposal** and **how to become a CA**. With intent for my community -and others in their own languages- to have a baseline understanding of how things might work."_

Link for **How To Propose a Proposal** : https://docs.google.com/document/d/1zvk6UWk_Q6n88RPoPz2_4AACvLrchFcbhlFggNbGAtU/edit?usp=sharing

Link for **How To Become a CA** :
https://docs.google.com/document/d/1NpIMAiUAS_cJC3EcoaRMKYml4L6YyYfJ0bplkq8sEK4/edit?usp=sharing

**Comment by wolstaeb** [comment]
Thanks @YanTirta I'll turn these into markdown files in a documentation repo. These will then be pulled into the website.

> kindly find the translated document that we previously talked about.

**Comment by PardusEidolon** [comment]
> @wolstaeb , kindly find the translated document that we previously talked about. With a short reminder, _"we agreed to have a tab on the landing page that translates on **how to propose a proposal** and **how to become a CA**. With intent for my community -and others in their own languages- to have a baseline understanding of how things might work."_
> 
> Link for **How To Propose a Proposal** : https://docs.google.com/document/d/1zvk6UWk_Q6n88RPoPz2_4AACvLrchFcbhlFggNbGAtU/edit?usp=sharing
> 
> Link for **How To Become a CA** :
> https://docs.google.com/document/d/1NpIMAiUAS_cJC3EcoaRMKYml4L6YyYfJ0bplkq8sEK4/edit?usp=sharing

Hi @YanTirta, do you have the links to the original source documents you translated these from?

**Comment by YanTirta** [comment]
I do, please kindly find the original sources @PardusEidolon :
How To Propose a Proposal :
https://docs.google.com/document/d/1oE_cnP0gksdAanXV4w5DYaDNp_tbYEvyHhTUG4HYZ3Q/edit?disco=AAAAG42-Ypk&usp_dm=true

How To Become a CA :
https://cardanocataly.st/community-advisor/guide.html

**Comment by PardusEidolon** [comment]
> I do, please kindly find the original sources @PardusEidolon :
> **How To Propose a Proposal :**
> https://docs.google.com/document/d/1oE_cnP0gksdAanXV4w5DYaDNp_tbYEvyHhTUG4HYZ3Q/edit?disco=AAAAG42-Ypk&usp_dm=true
> 
> **How To Become a CA :**
> https://cardanocataly.st/community-advisor/guide.html

Thanks!
