### ISSUE TITLE
Eastern Hemisphere Organisation - 14th August, 2021 - 8 to 10 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#20]
### Eastern Hemisphere Organisation - 14th August 2021 - 8 to 10 UTC
- Last Meeting -  https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/19
- Next Meeting - https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/29

### Attendees
- Yan Tirta - INA - Indonesia 
- Robert O'Brien - EN - NZ
- Tim O'Brien - VN - Vietnam
- My Tran  - VN - Vietnam
- Greg Bell  - EN - Aus
- Jordy Vincent - INA - Indonesia 
- Andy Emurgo - INA - Indonesia 
- Felix Weber - EN 
- Stephen Whitenstall - EN
- Sunsuke Mursaki -  JP - Japan
- Tevo Saks - EN 
- Seomon Blub - EN 

## Apologies
- Skip - JP - Japan
- Yuta Yuta - JP - Japan

### General Notes
- A common stage for Eastern Hemisphere Catalyst communities. We establish and evolve the format as each community wishes - to counter disproportionate Western representation -  Felix
- English to come last - Tim O'Brien
- Cardano is owned by community - as part of Emurgo wish to share as much possible - for translations etc. If there is anything Emurgo can help - Sunsuke Mursaki -  JP - Japan

#### 1. Review of Thursday's Townhall: feedback, changes.
- English breakout - have 15 minutes of talking at the beginning to provide context - Robert O'Brien, Greg Bell
- Without live translation concerned opening would be drawn out - Greg Bell
- If our translators are up for live translation I would be open to give that a try - Greg Bell
- Jordy has more experience in live translation - Yan Tirta
- Get text in English translated - our presentation this week is from our Ind or Vietnam community  - Greg Bell
- 3 minutes max intro - Greg Bell, Robert O'Brien
- If we let community who provides script have their say - let communities rotate - Greg
- Just try one to begin with -  Robert O'Brien
- Link to Fund 6 value on-boarding proposal ? - Felix
- Most focus is on Stake-pool Operators - maybe we should orient participants to Project Catalyst - Felix
- Which community would like to provide script for next Town Hall - Greg Bell
- Vietnam group to organize a Town Hall script - Greg Bell
- Next Town Hall after that an Indonesian Town Hall Script - Yan Tirta
- We will rotate Town Hall Script per community each week - Greg Bell
- We need to request participants not to share their own link - to avoid lags and bugs - Felix
- Get Jack to do a graphic / animation on how to use Zoom interface and translate it - Robert O'Brien
- When we get breakout rooms with more than 20 people - have additional rooms for specific and focused topics - Felix
- A separate room for technical discussions - Robert O'Brien
- Each community will have its own additional room preferences - Greg Bell
- Catalyst School participation in breakout rooms - Felix
- I need to go to two or three sessions of Tevo's mini-proposal workshop before introducing into ETH sessions - Yan Tirta
- A mini-proposal is a reduced version of a main proposal with a reduced budget - that can be workshop in a structured way - Felix
- Yan Tirta and Andy Emurgo we can take a day to create an entire proposal - Tevo Saks
- Tuesdays and Thursdays are good for me - Andy Emurgo
- 6am UTC - Tuesday 17th August 2021 - for mini-proposal workshop - Tevo, Yan and Andy

####  2. Next ETH Video Lovebomb recording
- Setup our rooms to do Lovebomb recording - Robert O'Brien
- Felix and Day to record gallery view
- Can we  add "Meet Mie from Vietnamese community ... " etc 
- Have a separate room to record Lovebomb - Robert O'Brien
- Ask people if they want to switch cameras off in main room - Robert O'Brien

####  3. Soundbites for Daniel
- Soundbite summary for newsletters that go out every Friday - Robert O'Brien
- Create GitHub issue for Newsletter and add summary content there - so Dany can pull out what he wants - Robert O'Brien

####  4. Website Update and Translations
- Use Hugo Static Site generator for our website and documentation -  Robert O'Brien

#### 5. Fund 6 Campaign Translations
- Draft Fund 6 Proposals 

#### 6. Fund 6 Suggested GitHub/Crowdin workflow
- Use https://crowdin.com/ to automate translation - Robert O'Brien
- crowdin has an open-source concession - Robert O'Brien
- Blog posts, documentation - Robert O'Brien
- Jack can do tuition video for crowdin  - Robert O'Brien

#### 7. Fund 6 Challenge Setting Proposal(s): Language-specific challenges
- Translate all the Campaigns using c3eth-fund6 repository 
- https://github.com/C3ETH/c3eth-fund6 repository  - Robert O'Brien

#### 8. Fund 6 ETH Proposal(s) ideation insights  
- Community Challenge setting for Fund 7 - language specific challenge - Robert O'Brien
- Keep Community Challenge small - but how many for Fund 7 - Robert O'Brien
- Return on intention is international participation - Greg Bell
- Would be positive to prepare content creation - if it can start from Indonesian community - this would help onboard local people - Jordy Vincent
- Draft a Fund 7 Challenge Setting - Greg Bell, Robert O'Brien
- If anyone who wants to draft insights this week as well - Robert O'Brien
- Encourage everyone to draft insights to raise our profile and receive feedback - Stephen

#### 9. Fund 6 ETH Proposal(s) ideation 
- A fund to act as a bounty for translation of proposal  - Robert O'Brien
- Can help with proof-reading of proposals in English - Greg Bell
- ETH Branding of proposals - in separate proposals - lets put in multiple proposals and see what people vote for - Greg Bell
- Mini-Proposal was about offering bounties for community contribution - Tevo Saks
- Local Community centers proposal - Greg Bell
- Map multiple proposals on miro board - Seomon 
- https://miro.com/app/board/o9J_l2_uFQI=/
- Can we ideate proposals using insights - Robert O'Brien
- We can submit insights on Ideascale now - Greg Bell
- Submit insights on Ideascale then copy to GitHub repo - Robert O'Brien
- There will be proposals by local groups - this might split the vote - Tim O'Brien
- If that happens we approach proposer to merge - Robert O'Brien
- Figure out what needs to be done by doing - Robert O'Brien
- We are using insights to ideate - Robert O'Brien

#### Another Other Business

- Eastern Town Hall Workshop for Catalyst School - Seomon

#### ETH Participation
EHT  | Date | Registrations | Participants |   | Japan | Indonesia | Vietnam | English | Korean
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |  
EHT 1 | 29/07/2021 | 86 | 47 |   | 15 | 14 | 5 | 7 | -
EHT 2 | 05/08/2021 |   | 64 |   | 11 | 11 | 32 | 12 | -
EHT 3 | 12/08/2021 | 335 | 93 |   | 43 | 10 | 29 | 11 | -

### Next Meeting Topics

**Comment by wolstaeb** [comment]
A comment from @tuvalusoftware (via email) as he was I was unclear on one point. 

> Are you writing one proposal for translation services for all countries: Japan, Indonesia, Vietnam, korea..  or are.writing one proposal for each country. 

Nothing is decided yet in that area specifically.

What we did discuss was writing one proposal for the Challenge Setting Challenge (Challenges for Fund7) that is customised to each language. Each customisation then becomes a separate challenge setting proposal. These will initially have small budgets to kick-start language-specific challenges into the future. 

> My initial thoughts were that there would be a kind of operations budget that would cover translators and full-time workers. 

Tevo raised the idea of using some of his current F5 funds as a translation bounty. The idea of using bounties to pay for translations is potentially a proposal that we can put up. What struck me when Tevo raised the idea was that we should be able to use the very tools of Cardano (Metadata, NTFs & Mutli-Assets, and Smart contracts) to help crowd-source translations.

**Comment by tuvalusoftware** [comment]
Hi, after a  discussion with Robert I wanted to put some thoughts down on the translation proposals. 
It seems to me that Vietnam, being a country that is still in the early stages of awareness of Cardano and Blockchain, is more dependent on an undiluted Town Hall brand to win votes from the global ADA holders- we are somewhat more reliant ADA holders of our neighbors like Japan, Indonesia,etc., as well as the global ADA holder to put Vietnamese proposals over the top. 

I see three distinct expense buckets

   (i)   expense  of townhall translators 
   (ii)  expense  of translating documents
   (iii) expense of translation framework &  analysis, approval, governance etc. 

 I think an optimal distribution of expenses in these buckeds would be: 

(i)   administrative expense - at the same expense as paying the moderators - including  Felix, Yan... 
(ii)   local proposals should be given precedence. 
(iii). seems like worthy of being its own proposal, or group it in with (i) 

I also want to consider the independence of the Town Halls. This has nothing to do with the individuals involved, I trust implicitly on the team's good intentions but we are setting 
a precedent of centralized economic control that is against the grain of what the Town Hall is about. This is why I think any proposals not written by the local Town Halls themselves, should be tagged as the bundled expenses of running the Town Halls, i.e.,  (1) in the above list.
