### ISSUE TITLE
ETH Proposal Workshop -  Wednesday, 18th August 2021 - UTC 8:00AM to UTC 10:00AM

### ISSUE THREAD

**Issue by stephen-rowan** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#29]
## ETH Proposal Workshop - Wednesday, 18th August 2021 - UTC 8:00AM to UTC 10:00AM

Our objective is to work on the C3 ETH Catalyst Fund 6 Proposals in the workshop. 

- Last Meeting - https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/20
- Next Meeting - #31 

# Table of Contents
- [Table of Contents](#table-of-contents)
  - [Attendees](#attendees)
  - [Workshop Notes](#workshop-notes)
  - [Some Background](#some-background)
  - [Miro Proposal Ideation](#miro-proposal-ideation)
  - [Insights Gathered](#insights-gathered)
  - [Adhoc Analysis](#adhoc-analysis)
  - [Proposal Submittion to Ideascale](#proposal-submittion-to-ideascale)
  - [Proposal Budget Structures](#proposal-budget-structures)
  - [Working in with other groups.](#working-in-with-other-groups)
  - [Concerns and Goals for C3ETH Proposals](#concerns-and-goals-for-c3eth-proposals)
    - [Relative voting power](#relative-voting-power)
    - [Retroactive Funding](#retroactive-funding)
  - [Catalyst Challenge Teams and Rapid Funding](#catalyst-challenge-teams-and-rapid-funding)
    - [Doing too much too soon](#doing-too-much-too-soon)
  - [Challege Setting](#challege-setting)
    - [Language Specific Challenges](#language-specific-challenges)
  - [Multilingual Challenge](#multilingual-challenge)
  - [Distributed Decission Making](#distributed-decission-making)
  - [Proposer Outreach and Value Onboarding](#proposer-outreach-and-value-onboarding)
  - [Notes on experiments with translation](#notes-on-experiments-with-translation)

## Attendees
- Robert O'Brien (@wolstaeb) - EN
- Felix Weber (@FelixfromSwarm) - EN 
- Seomon Blub (@Seomon4u)  - EN 

## Workshop Notes

Our objective was to work on the C3 ETH Catalyst Fund 6 Proposals in the workshop. 

1. Fund 6 ETH Proposal(s) ideation insights  
2. Fund 6 Challenge Setting Proposal(s): Language-specific challenges
3. Fund 6 ETH Proposal(s) ideation 

## Some Background

@YanTirta, @zicozibu are doing a workshop with Tevo to go over the mini-proposal proposal workshopping process before introducing it into ETH sessions. A mini-proposal is a reduced version of the main proposal with a reduced budget - that can be workshopped in a structured way. The suggestion is that this process will be a great way to start ideation of the C3 ETH proposals.

If @C3ETH/c3eth-team can draft insights this week- and we encourage everyone to draft insights to raise our profile and receive feedback- these will become our starting point for developing the full/mini proposals. Ideate the proposals using insights on Ideascale then copy them over to the [Fund6 Proposal GitHub repo](https://github.com/C3ETH/c3eth-fund6).

## Miro Proposal Ideation

Since there is potential for overlap with Catalyst Swarm, and Catalyst School, we will map out the multiple proposals on [miro board](https://miro.com/app/board/o9J_l2_uFQI=/)

## Insights Gathered

Catalyst Fund 6 insights have been gathered. Some were authored by members of C3ETH, others just found to be interest or relevant. You can find these in the īnsights.md` files are listed below. Insights from C3ETH participants identify the proposer. Links to the individual insights on IdeaScale are included.

- [Atala PRISM DID Mass-Scale Adoption](blob/main/atala-prism-did/insights.md)
- [Catalyst value onboarding](blob/main/catalyst-value-onboarding/insights.md)
- [Developer ecosystem](blob/main/developer-ecosystem/insights.md)
- [Distributed decision making](blob/main/distributed-decision/insights.md)
- [DLT Entrepreneurship Toolbox](blob/main/dlt-enterpreneurship/insights.md)
- [Fund7 challenge setting](blob/main/fund7-challenge-setting/insights.md)
- [Improve and Grow Auditability](blob/main/improve-auditability/insights.md)
- [Metadata challenge](blob/main/metadata-challenge/insights.md)
- [Multilingual resources](blob/main/multilingual-resources/insights.md)
- [NFT Business models](blob/main/nft-business-models/insights.md)
- [Partnerships for Global Adoption](blob/main/partnerships-for-adoption/insights.md)
- [Proposer outreach](blob/main/proposer-outreach/insights.md)
- [Scale-UP Cardano's Community Hubs](blob/main/scaleup-community-hubs/insights.md)

In some cases, relevant comments, additional information, and related insights have been added. **NOTE**: *This is not a definitive collection of insights from Ideascale. It is curated.* This collection of insights are from Fund 6 only. Only in some instances have prior fund proposals and insights are referenced. If time/energy permitted a more extensive analysis would be useful.

## Adhoc Analysis

Several patterns or trends are evident from looking at the insights to date.

1. Many proposers are aiming to create and/or translate content.
2. Insights related to impact measurement & reporting occur often.
3. Many Community groups have similar funding needs
4. How to fund projects especially when outputs are not as concrete.

## Proposal Submission to Ideascale

Following the lead of CatalystSwarm to have a distinct profile on Ideascale for submitting proposals:

- Setup Ideascale Catalyst Eastern Townhall Account
- The profile will be the Primary Submitter with additional C3ETH people listed
- Common Gmail Email account (eastern dot townhall at Gmail dot com)
- Proposals will follow a common template/format.

The C3ETH specific proposals will be non-technical. Typically covering four main deliverables.

1. Localised content creation.
2. Translation of content.
3. Interpretation of sessions
4. Delivery: Running the Townhalls, meetings, and workshops

## Proposal Budget Structures

We had some discussion around better funding mechanisms be recognised the limitations of the current Catalyst process to fund retroactive work and ongoing effort. Some discussion in particular around paying for the efforts of the participants. Ideally...

1. Projects like the C3ETH would be DAOs.
2. Catalyst Proposal Inversion Mechanisms are needed
3. Such mechanisms aren't simple to implement. For instance, because there is likely KYC/AML considerations
4. Collaborative Accounting Mechanisms should be explored ( [SourceCred](https://sourcecred.io/), [Coordinape](https://coordinape.com/) )

The Fund 6 proposal(s) need to work within these limitations for the moment. Recognising the insufficient and incomplete nature of tools required to work together in a decentralised globally distributed fashion.

Budget structure needs to:

- Consider Payments to those involved
- Cover Direct Costs. 
- The *ask* sweet spot is %16 - %20 of challenge funds

Examples of direct costs (requiring conversion into a national currency) include using:

1. Paying for translations and interpretation (if not sourced within C3ETH)
2. Domain Name(s)
3. Hosting
4. Zoom Business Account
5. CrowdIn
6. Meetup (or Similar)

## Working in with other groups.

In the numerous discussions, it has been highlighted the cross-over with other community groups in Catalyst.
The challenges themselves are competitive, however, there is nothing preventing us from taking a collaborative approach. After all, in most case, we are creating public goods for the Cardano Ecosystem. They have similar goals to broaden the reach of the Cardano Catalyst Ecosystem. The three groups often
discussed because there is plenty of overlap in memberships:

1. Catalyst Swarm 
2. Catalyst School
3. QA DAO

It seems pointless to work on competing proposals. However, in the spirit of decentralising governance, it is not considered desirable to coordinate under a single umbrella proposal. Local needs and specific focus will vary. The proposals themselves will have a similar focus and structure. Therefore we'd like to work on and develop common template proposals with these other community groups. The proposals would then be tweaked (customised) to each group's local needs.

In many cases, for instance, local language groups, these proposals while similar are non-rivalrous. C3ETH voters are more likely to vote for C3ETH proposals because they cater to the C3ETH's local members.

### Relative voting power

The relative voting strengths of each language/country group in the C3ETH timezone. An important issue to consider. @tuvalusoftware in [prior comments](https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/20#issuecomment-899031823) the disadvantage that countries like Vietnam (and @wolstaeb notes New Zealand too) have relative to larger countries in the hemisphere. Whether because of awareness or size. If the proposal's focused on specific countries and languages then countries like Vietnam would be at a significant disadvantage. **Unified proposals** would be much better. At least in the beginning.

### Retroactive Funding

In a prior meeting, Greg discussed the budget structure of the proposals should contain an allowance for %50 retroactive funding. That is because we are already trying to get the ETH off the ground. Proposal development takes significant time too. This is an issue for public goods funding in general. When there isn't a *business model* that justified risk-taking many community efforts fail because they rely on altruism. And that is not sustainable.

## Catalyst Challenge Teams and Rapid Funding

Only incidentally related to the ideation of proposals, we discussed the idea and objectives of the [Challenge Teams](https://docs.google.com/document/d/1GDCKOysG1dd4nUXYcio3PY889doGrbC34PFggu8FI20/edit#heading=h.dxixtumushib) and [Rapid Funding](https://docs.google.com/document/d/1jC_aUmJmiZEudPMrJt64fFbBXNIiDSxQrrMJC7xqz_4/). These directly touch on issues concerning retroactive funding, and inverted proposals mentioned above.

- Challenge: Defined by a Challenge Team
- Challenge Team: A group of people tasked with coordinating a Catalyst Challenge.
- Rapid Funding: Experimenting with alternative models for Catalyst funding.

For fund 6 we are not considering C3ETH as a challenge team or a candidate for rapid funding. However, for future proposals, we may want to consider alternative funding models to experiment.

### Doing too much too soon 

The C3ETH is young. Very young and we are still trying to figure out how to work together. There are different skill sets, different languages, and widely different cultures. While this is **beautiful** it does make understanding and coordinating more difficult. Western cultures for instance share many cultural similarities, ditto shared language communities such as Spanish.

In the C3ETH we bridge many languages and cultures. Be careful in how much we attempt to take on. Take time to understand each other, make sure everyone is welcome and able to find a way to contribute. While there is a desire to do a number of proposals, less is more. Until we plant our feet firmly.

### Language-Specific Challenges

In [prior dicussion](https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/20) we had settled on a format for language-specific challenges. [Start-small and grow from there.](https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/15) Asking for Challenge Funds of say $75K USD. This would enable onboarding to start without placing too much onus on C3ETH participants to coordinate. The multi-language proposal's themselves would be unified by virtue of coming from C3ETH.

On reflection of @tuvalusoftware in [relative voting power comments](Catalyst-Eastern-Hemisphere-Co-Ordination/issues/20#issuecomment-899031823) an alternative approach was suggested - adopt and adapt the [Grow Cardano, Grow Africa](https://cardano.ideascale.com/a/dtd/Grow-Africa-Grow-Cardano/333079-48088) proposal for South-East Asia.

[Just copy it more-or-less](https://cardano.ideascale.com/a/dtd/Grow-Africa-Grow-Cardano/333079-48088).

## Multilingual Challenge

Many community groups and IOG/CF/Ideascale want to translate content. However, coordinating efforts to do that through a single coordinating group is difficult to pull off and counter to ideas of decentralised governance/control. So how to approach this while not replicating effort?

The general approach is to lead by example, make it open, and help establish a shared approach that ensures details can be easily integrated/share. In our C3ETH case, we are uniquely positioned because we are from the beginning dealing with multiple languages. English is not a first, or fast second language, across the eastern hemisphere. We are not oriented around a common language like the Spanish community for instance.

To serve our own needs @wolstaeb is asking the C3ETH participants to use some tools and processes not familiar to many members of the group. Git, Github, Markdown, and Crowdin. These will take time to learn and let people become accustomed to them. However these tools are proven to work in global knowledge creation- Open Source Software development- therefore provide a good basis for standardising localisation practice.

In addition, @wolstaeb and @FelixfromSwarm have had discussions with the Spanish Community, and IOG staff. Clearly, there is a need to do something in common using the C3ETH as the initial example.

## Distributed Decision Making

Building upon all the prior discussion, the C3ETH efforts fit this challenge from the point of view of helping to:

1. CA Onboarding/Understanding
2. Increase participation and Voting

Within the Eastern Hemisphere, and South East Asia specifically. There is significant overlap with the Catalyst School in any proposal in this challenge. Please refer to the [miro board](https://miro.com/app/board/o9J_l2_uFQI=/) and [Catalyst School proposal development](https://docs.google.com/document/d/18iZSUnR3eJyQz6MvxH8vpnpy4vUA8GVnu0-K3sejXIs/edit).

Additional orientation notes will be added here when these have been reviewed.

## Proposer Outreach and Value Onboarding

[Proposer Outreach](blob/main/proposer-outreach/campaign-brief.md) and [Value Onboarding](blob/main/catalyst-value-onboarding/campaign-brief.md) are two challenges that in general the C3ETH fall. By running the Eastern Townhall we aim to do introduce the community to: 

1. Cardano
2. Catalyst
3. Being a proposer
4. Being a Catalyst Community Advisor

How we do that is going to be an evolving format. Centred initially and primarily on the unified Eastern Townhall and language-specific breakout room format. We will take cues from the Catalyst Swarm, and hopefully also provide cues and ideas back to them also. For example, @whitevo has been helping C3ETH members (@YanTirta and @zicozibu) understand the mini-proposal format and process.

There is significant overlap with the Catalyst Swarm and Catalyst School in any proposal in these challenges. Please refer to the [miro board](https://miro.com/app/board/o9J_l2_uFQI=/) and [Catalyst School proposal development](https://docs.google.com/document/d/18iZSUnR3eJyQz6MvxH8vpnpy4vUA8GVnu0-K3sejXIs/edit).

Additional orientation notes will be added here when these have been reviewed.

## Notes on experiments with translation

Please start translating the Campaigns in the [Fund6 Proposal GitHub repo](https://github.com/C3ETH/c3eth-fund6). There is a [public translation project in Crowdin](https://crowdin.com/project/c3eth-fund6) to help streamline the translation of the [Catalyst Fund 6 Challenges](https://github.com/C3ETH/c3eth-fund6) and our work developing proposals for Fund 6. We are trying things out using [Crowdin](https://crowdin.com/project/c3eth-fund6), [Github](https://github.com/C3ETH/c3eth-fund6), and [markdown](https://guides.github.com/features/mastering) files.

The [Crowdin project](https://crowdin.com/project/c3eth-fund6) is pulling the English source files (markdown) from the  [Catalyst Fund 6](https://github.com/C3ETH/c3eth-fund6) repository. If all goes well we should be able to crowdsource translations and offer bounties 😁 and NFT achievement badges eventually. The following languages have been set up for translations, more can be added:

- Indonesian
- Japanese
- Korean
- Vietnamese
- Māori
- French
- German

If you go to https://crowdin.com/project/c3eth-fund6 and sign up to Crowdin you should be able to pick the language and start translating the Catalyst Fund 6 Challenges into your language. Have a go and try it out. 

Please let me know what email you used to signup to Crowdin so I can add you as a team translator if needed. That way you'll be able to send the link to the public project out and get other people to help out. You will be able to go through and approve their translations before they end up back in the main repository. Periodically I will pull the translations back into the main [Catalyst Fund 6](https://github.com/C3ETH/c3eth-fund6) repository and merge them. More details are in the [README file](https://github.com/C3ETH/c3eth-fund6). Any questions you can either put them into the Eastern Townhall Discord or Crowdin has chat/message features.

**Comment by wolstaeb** [comment]
@C3ETH/c3eth-team has a time been agreed for this. I'm able to attend anywhere from 6:00 AM UTC until 12:00 PM UTC on Tuesday. If I recall from discussion in the meeting #20, the best time was 8:00AM UTC onward for Greg.

**Comment by wolstaeb** [comment]
Some comments from @tuvalusoftware that are relevant to this session https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/20#issuecomment-899031823

### A quick summary 

- Vietnam in the early stages of awareness of Cardano and Blockchain.
- An undiluted Town Hall brand helps Vietnam
- Three distinct expense buckets for translators and translation framework & analysis, approval, governance.
- An optimal distribution of expenses would be among administrative and local proposals.
- Independence of the Town Halls. We are setting a precedent of centralized economic control. 
- Any proposals not written by the local Town Halls themselves, should be grouped with the bundled expenses.
