### ISSUE TITLE
Eastern Hemisphere Townhall Meeting - Thursday 19th - UTC 12:00 to 14:00 PM

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#31]
## Eastern Hemisphere Townhall Meeting - Thursday 19th - UTC 12:00 to 14:00 PM

![2021-08-19 (7)](https://user-images.githubusercontent.com/25156451/130091870-197ec11a-c9c4-42ef-b6fd-468eca92ffbc.png)

- Last Meeting: #29 
- Next Meeting: https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/32

- **[Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)** 
- **[Meeting Welcome Slides](https://docs.google.com/presentation/d/1XH9lyFk_Rv1MpidLhqCkdjKYbGVOXD2QGhgME9fbWgI/edit#slide=id.ge559e9bfcb_0_1687)**
- **[Breakout Room Video Guide](https://www.youtube.com/watch?v=3WRP-XD5-Yw)** (this is already embedded in the presentation).

## Meeting Soundbite

In this week's Eastern Town Hall, the Catalyst School ran the 'Proposing in Catalyst' session hosted by Raz. 90% of Indonesian participants attended. In the Viet Nam breakout room, Mercy from WADA was the guest, sharing her experiences. Proposals were shared and advice was gathered in all the breakout rooms. We also covered how to bring more women into Cardano and explored the opportunities for the creative economy.

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yan Tirta (@YanTirta)  - INA 
- Tim O'Brien (@tuvalusoftware )- VN
- Mie Tran (@Mietran0407) - VN
- Yuta Yuta - JP - Japan
- Robert O'Brien  (@wolstaeb) - EN 
- Greg Bell  - EN 
- Felix Weber (@FelixfromSwarm) - EN 
- Seomon Blub  (@Seomon4u) - EN 
- Daniel Ribar - EN

### Indonesian

An interesting turn of events happened where 90% of the Indonesian participants attended the Catalyst School breakout room. Numbers although mimic last week attendance, there was 1 new Indonesian speaking only participant who came from a family of traders. Due to this will expand marketing efforts into the coin communities for next week's Town Hall.

### Japan

[**TO BE DONE**]: fill out after the meeting. 

### Vietnam

In the Fourth Eastern Townhall, Viet Nam breakout room has 21 members coming, we invited Mercy from WADA to share her proposals and her experiences. A lot of questions showed up with great engagement and learning spirit to get to know the process and her difficulties with the proposals. A member shared his slide for his ready-to-submit proposal and asking for advice from the community. Many came up with ideas for discussing and contact other people for help. We may invite more interesting people to share and inspire people in the next meeting!

### Korea

**NOTE:** We forgot to set up a Korean room!

### English

[Townhall#2 Fund 6 Summary](https://docs.google.com/presentation/d/1D-xQRzGkLEbRNuQVtp4GG3V8NhSypsYyqTglcet1lQo/edit?usp=sharing)

The catalyst open innovation process is quite a different approach to developing your typical process of seeking funding. Keeping your ideas close versus opening up and collaborating. Questions on the logistics around the execution of funded proposals were discussed. We also covered how to bring more women into the town hall and answered the about creative economy proposals and opportunities for that space. 

### Catalyst School

[**TO BE DONE**]: fill out after the meeting. 

## Run sheet

1. Open room and welcome people.
2. Welcome Slides (MC Greg)
3. Weclome to the experiment in the respective languages.
4. Catalyst School
5. Video Recording of Group( ETH LoveBomb ?)
6. Townhall links 
7. Go to Breakout Rooms (Play Video Guide on loop)

## Additional Links and resources

- [Townhall#2 Fund6 Youtube Meeting](https://www.youtube.com/watch?v=josSLLQKZZ4)
- [Townhall#2 Fund6 Slides](https://docs.google.com/presentation/d/1nKfCxEIZmVsd5iAro7rTlqdy8MHdk-8fplsp4dANHqY/edit#slide=id.ge81f00c658_1_21)
- [Catalyst Ciricle  Rapid Funding TH#2 Fund6](https://docs.google.com/presentation/d/1nKfCxEIZmVsd5iAro7rTlqdy8MHdk-8fplsp4dANHqY/edit#slide=id.ge81f00c658_7_5991)
- [Catalyst School TH#2 Fund6 ](https://docs.google.com/presentation/d/1nKfCxEIZmVsd5iAro7rTlqdy8MHdk-8fplsp4dANHqY/edit#slide=id.ge81f00c658_7_5555)
- [Entreprenerdy Tools](https://tools.entreprenerdy.com/)
- [Ada Makerspace](https://adamaker.space/open-source-experiential-learning%e2%80%8b/#seeSchedulle)

## Catalyst School

Today there will be a breakout room  'Proposing in Catalyst' session in the Eastern Town Hall (ETH) hosted by Raz from Catalyst School:

- [Catalyst School Feedback](https://forms.gle/mynCvxu1a679zN859)

The Catalyst School is in a 'Pilot' stage right now and all feedback is welcome, so please feel free to do so. And if you've been to any of our sessions, please let us know as well!

## Eastern Town Hall Social Media Links
 
- Zoom: https://tinyurl.com/Eastern-Townhall-Zoom
- Telegram: https://t.me/joinchat/ODKTOvGnrHEwNTc6
- Discord: https://discord.gg/6T825EyvrG
- Email: eastern.townhall@gmail.com

## Town Hall Social Media Links

**Recurring Registration link**: https://bit.ly/3rCicSR add to your calendars and just simply join each week using the same access.

**Fund6 Challenges Overview**: https://www.youtube.com/watch?v=crs3lVaGejY&t=1821s

**Fund4+5 Feedback Form**: https://forms.gle/CGLwyskXr5Zusdp97  

**Use Discord**

Pitch-Devs Channel https://discord.gg/eJySdx9n6r or use:
@dev-for-hire to ping developers
@designer-for-hire to ping designers

Official proposer guide: https://bit.ly/3AX2sxf 
Proposer guide by Anthony

Proposer TG channel: https://t.me/catalystproposers

Community web 1: https://projectcatalyst.org/resources/proposer 

Community web 2: https://cardanocataly.st/proposers/  

CA Guide (to know how proposals are evaluated in Fund5): https://bit.ly/3iTfWns

Read the guidelines: https://docs.google.com/document/d/1oE_cnP0gksdAanXV4w5DYaDNp_tbYEvyHhTUG4HYZ3Q/edit 

Submit your proposal: http://cardano.ideascale.com/ 

Catalyst announcement channel: https://t.me/cardanocatalyst 

Catalyst Proposers channel on telegram: https://t.me/catalystproposers

**Comment by stephen-rowan** [comment]
Great preparation Robert :)

**Comment by YanTirta** [comment]
**Indonesian Soundbite** : An interesting turn of events happened where 90% of the Indonesian participants attended the Catalyst School breakout room. Numbers although mimic last week attendance, there was 1 new Indonesian speaking only participant who came from a family of traders. Due to this will expand marketing efforts into the coin communities for next week's Town Hall.

**Comment by Mietran0407** [comment]
**Vietnamese Soundbite**: In the Fourth Eastern Townhall, Viet Nam breakout room has 21 members coming, we invited Mercy from WADA to share her proposals and her experiences. A lot of questions showed up with great engagement and learning spirit to get to know the process and her difficulties with the proposals. A member shared his slide for his ready-to-submit proposal and asking for advice from the community. Many came up with ideas for discussing and contact other people for help. We may invite more interesting people to share and inspire people in the next meeting!

**Comment by wolstaeb** [comment]
@all-contributors please add @Mietran0407  for eventOrganizing and translation

**Comment by wolstaeb** [comment]
@all-contributors please add @YanTirta for eventOrganizing and translation. And taking sole charge of the Indonesian breakout room.

@all-contributors please add @tuvalusoftware  for eventOrganizing.

@all-contributors please add @stephen-rowan for eventOrganizing and 📆
projectManagement and doc. Just doing an awesome job with keeping track of everything.

@all-contributors please add @FelixfromSwarm for eventOrganizing and mentoring.

@all-contributors please add @grebel_au for eventOrganizing.

@all-contributors please add @wolstaeb for eventOrganizing, projectManagement, infra.

**Comment by wolstaeb** [comment]
@all-contributors please add @YanTirta for eventOrganizing and translation. And taking sole charge of the Indonesian breakout room.

**Comment by wolstaeb** [comment]
@all-contributors please add @tuvalusoftware for eventOrganizing.

**Comment by wolstaeb** [comment]
@all-contributors please add @stephen-rowan for eventOrganizing and 📆
projectManagement and doc. Just doing an awesome job with keeping track of everything.

**Comment by wolstaeb** [comment]
@all-contributors please add @FelixfromSwarm for eventOrganizing and mentoring. And just for being an awesome community wrangler. The person we need to give us confidence in ourselves.

**Comment by wolstaeb** [comment]
@all-contributors please add @grebel_au for eventOrganizing and being a great co-host.

**Comment by wolstaeb** [comment]
@all-contributors please add @grebel-au for eventOrganizing and being a great co-host.

**Comment by wolstaeb** [comment]
@all-contributors please add @wolstaeb for eventOrganizing, projectManagement, infra.
