### ISSUE TITLE
Eastern Hemisphere Meeting - Saturday 28th August 08:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#45]
## Eastern Hemisphere Meeting - Saturday 28th August 08:00 UTC

ETH Planning/Workshop Meeting. Our objective is to discuss and work on the drafts of the C3 ETH Catalyst Fund 6 Proposals.

- **[Meeting Link](https://us02web.zoom.us/j/84374449716?pwd=emNHcXpHYWIzM3h5dW1NS3dnaFFSdz09)** 

- Last Meeting - #41  
- Next Meeting - #44 

- Last Proposal Workshop - #43 

###  Attendees

- Yan Tirta (@YanTirta) - INA
- Tim O'Brien (@tuvalusoftware )- VN
- Robert O'Brien (@wolstaeb) - EN
- Felix Weber (@FelixfromSwarm) - EN
- Seomon Blub (@Seomon4u) - EN
- Stephen Whitenstall (@stephen-rowan)

### Apologies

- Mie Tran (@Mietran0407) - VN
- Skip - JP 

### Agenda

Review and discussion on the following proposals:
 
3. [Distributed Decision Making](https://hackmd.io/@c3eth-team/ry8XMgGbF/edit)
4. [Proposer Outreach](https://hackmd.io/@c3eth-team/SJD6SlzZK/edit) 
5. [Value Onboarding](https://hackmd.io/@c3eth-team/HJ_vUxf-K/edit)

### Discussion Notes

Please see meeting notes for #42 for more details. This is a meeting is an opportunity to review and edit drafts of the proposals' *detailed plan* section for the following:

1. [Grow East Asia, Grow Cardano](https://hackmd.io/@c3eth-team/H1Nb8BAgt/edit)
2. [Multilingual Challenge](https://hackmd.io/@c3eth-team/B1pIyxfWt/edit) 
3. [Distributed Decision Making](https://hackmd.io/@c3eth-team/ry8XMgGbF/edit)
4. [Proposer Outreach](https://hackmd.io/@c3eth-team/SJD6SlzZK/edit) 
5. [Value Onboarding](https://hackmd.io/@c3eth-team/HJ_vUxf-K/edit)

### Budgets

**BUDGET:** [C3ETH Proposal(s) Budget Spreadsheet](https://docs.google.com/spreadsheets/d/1BeMc7BW9NFVSWPomM3j4Iv5I7Eveb24P-dFhFOUrCvo/edit?usp=sharing)

The fund amount for [Grow East Asia, Grow Cardano](https://hackmd.io/@c3eth-team/H1Nb8BAgt/edit) is $100K USD. The treasury fund for [Value Onboarding](https://hackmd.io/@c3eth-team/HJ_vUxf-K/edit) is $10K USD. Budgets for the other proposals need to be worked on:

- [Multilingual Challenge](https://hackmd.io/@c3eth-team/B1pIyxfWt/edit) 
- [Distributed Decision Making](https://hackmd.io/@c3eth-team/ry8XMgGbF/edit)
- [Proposer Outreach](https://hackmd.io/@c3eth-team/SJD6SlzZK/edit) 

Brief notes from #32 Proposal budgets need to consider.

- Roles and required Budget for each role.
- Commitments
- Website
- Marketing
- Content creation 

### Notes

- Update proposals - KPIs - Roadmap - Budget
- Think about script for video - 1 to 1minute 30
- Finish proposals by end of week 3rd September 2021
- Get ETH website up - and host extended information - by end of week 3rd September 2021
- Hugo theme - https://www.docsy.dev/

### Next Meeting Topics

- Proposal Budgets
- Roadmap/Plan
- KPIs

**Comment by stephen-rowan** [comment]
## Rough Notes

- Update proposals - KPIs - Roadmap - Budget
- Think about script for video - 1 to 1minute 30
- Finish by end of week 3rd September 2021

**Comment by Mietran0407** [comment]
My draft script for the 1:30s video.

Hello everyone! 

My name is Mie and I am from Viet Nam. I am part of the Cardano Eastern Townhall and also the translator of the Viet Nam breakout room.

It’s blooming that Cardano has spread its wing to East Asia and create more opportunities and roles to equalize the community and build up the decentralization system. It connects East Asia with the world

Catalyst project is growing fast with the number of proposals increasing double every fund, if we could optimize all the votes from ADA holders, the chance you get funded for a project is higher. Especially when the majority of the ADA holder is in Asia

However, there is a language barrier for those non-native English-speaking countries. It is difficult for them to fully understand the insight of the proposal and might easily overlook them and only vote along with the crowd. 

Our goal is to establish a process, format, and event stage for voter and proposer onboarding. To bring voters, proposers, and proposals closer together by building trust between them. This can be approached in many ways: help ADA holders understand why it is important to vote, give translation guidelines, socialize content, and conduct routine surveys.

I believe there will be many efficient ways to achieve the goal and you might be the one to bring it up. Help us improve decision-making across the Eastern Hemisphere by making Catalyst voting more accessible.
