### ISSUE TITLE
Eastern Hemisphere Meeting - Monday 30th August 08:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#46]
ETH Planning. Discuss the agenda for this week's town hall. Any questions and progress update on Catalyst Fund6  Proposals.

[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/84374449716?pwd=emNHcXpHYWIzM3h5dW1NS3dnaFFSdz09)

- Last Meeting - #45
- Next Meeting - 

### Proposed Attendees

- Yan Tirta (@YanTirta) - INA
- Tim O'Brien (@tuvalusoftware )- VN
- Mie Tran (@Mietran0407) - VN
- Skip - JP 
- Yuta Yuta - JP 
- Robert O'Brien (@wolstaeb) - EN
- Greg Bell ( @grebel_au ) - EN
- Felix Weber (@FelixfromSwarm) - EN
- Seomon Blub (@Seomon4u) - EN
- Stephen Whitenstall (@stephen-rowan)
- Andy Sibuea ( @zicozibu ) - INA

### Notes

Reminders on work needed for proposals. We need to update proposals with  KPIs,  Roadmap (Dates), and budget breakdown. We need to finish proposals by end of week 3rd September 2021 so we can translate them ASAP. 

We also want to do a short video (~1:00 minute) for each proposal that explains it quickly. The current suggestion is these videos feature the ETH Proposer discussing the key elements of the proposal. Please think about a script for each.

**Comment by stephen-rowan** [comment]
## Rough Notes

- Run sheet for for Thursday 2nd September 2021
- Which special guests should we invite the week after - Felix
- Everyone is in proposal mode - so we should adjust to what is going on in Catalyst - Felix

**Comment by wolstaeb** [comment]
Fund6 Innovation Phase.

![Screen Shot 2021-08-19 06 42 00 AM](https://user-images.githubusercontent.com/82072426/131312591-509f3cee-1688-4859-bcce-949646389730.png)

CA Signup: A popup will show up in IdeaScale from September 2nd until September 9th, just read and check the box accordingly, and keep an eye at the announcements around here (Discord) and on Telegram"

This is a great CA & vCA Video on the fund 6 rewarding model (@Seomon4u). https://www.youtube.com/watch?v=0ZKWagnFGZA
