### ISSUE TITLE
Eastern Hemisphere Townhall Meeting#7 - Thursday 9th September 12:00PM UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#47]
## Eastern Hemisphere Townhall Meeting#7 - Thursday 9th September 12:00PM UTC
![2021-09-09 (1)](https://user-images.githubusercontent.com/25156451/132685314-6ae0c73a-d655-44d3-8b8c-1b4d20625163.png)

- Last Meeting: https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/44
- Next Meeting: #49 49

- **[Meeting Link](https://zoom.us/meeting/register/tJIrcumprTssEtN_RkkiNfKkyWmKn2G65mX3)**
- **[Meeting Welcome Slides](https://docs.google.com/presentation/d/1XH9lyFk_Rv1MpidLhqCkdjKYbGVOXD2QGhgME9fbWgI/edit#slide=id.ge559e9bfcb_0_1687)**
- **[Breakout Room Video Guide](https://www.youtube.com/watch?v=3WRP-XD5-Yw)** (this is already embedded in the presentation).

## Meeting Soundbite

Across six breakout rooms, 95 participants had two hours of conversations. Regulars and new faces in all rooms. Aidan Rankin- Williams from Playermint share his journey with Catalyst. Victor Corcino veteran Community Advisor in Catalyst taking a CA Catalyst School session. Atala Prism, the underlying technology and applications was a topic of interest to many in the English breakout room. Great conversations all around. See you next Saturday at 09:00AM UTC for the next Eastern Townhall.

## Attendees

EHT # | Date | Registrations | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
EHT #1 | 29/07/2021 | 86 | 47 | 15 | 14 | 5 | 7 | - |  
EHT #2 | 05/08/2021 |   | 64 | 11 | 11 | 32 | 12 | - |  
EHT #3 | 12/08/2021 | 335 | 93 | 43 | 10 | 29 | 11 | - |  
EHT #4 | 19/08/2021 |   | 94 | 49 | 3 | 19 | 11 | - | 12
EHT #5 | 26/08/2021 |   | 62 | 35 | 7 | 10 | 10 | - | -
EHT #6 | 02/09/2021 |   | 76 | 31 | 6 | 22 | 14 | - | 3
EHT #7 | 09/09/2021 |   | 95 | 39 | 9 | 30 | 7 | 4 | 6

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yan Tirta (@YanTirta)  - INA 
- Tien Nguyen Anh - VN
- Tim O'Brien (@tuvalusoftware )- VN
- Mie Tran (@Mietran0407) - VN
- Yuta Yuta - JP - Japan
- Robert O'Brien  (@wolstaeb) - EN 
- Felix Weber (@FelixfromSwarm) - EN 
- Seomon Blub  (@Seomon4u) - EN 
- Daniel Ribar - EN
- Steve Lockhart - EN
- Victor Corcino
- Aidan Rankin-Williams

### Indonesian

[**TO BE DONE**]: fill out after the meeting. 
### Japan

[**TO BE DONE**]: fill out after the meeting. 
### Vietnam

Today's Vietnam town hall had 30 people coming. There are a lot of newcomers, we decided to spend the first 15 minutes of every town hall to introduce again what is Catalyst and how it works. Today we invited Aidan Rankin- Williams from Playermint to share his journey with Catalyst. Hope to get more people if the meeting moves to Saturday! Wish everyone a good night!

### Korea

[**TO BE DONE**]: fill out after the meeting. 
### English

Across six breakout rooms, 95 participants had two hours of conversations. Regulars and new faces in all rooms. Aidan Rankin- Williams from Playermint share his journey with Catalyst. Victor Corcino veteran Community Advisor in Catalyst taking a CA Catalyst School session. Atala Prism, the underlying technology and applications was a topic of interest to many. See you next Saturday at 09:00AM UTC for the next Eastern Townhall.

## Run sheet

1. Open room and welcome people.
2. Welcome Slides (MC Mie/Yan)
3. Weclome to the experiment in the respective languages.
4. Shoutout for CA in Catalyst (Felix)
5. CA Catalyst School
6. Go to Breakout Rooms (Play Video Guide on loop)

- Proposals to be finished
- Meeting Change week to Saturday @ 09:00 UTC
- Summit Video for proposer (email going out)

## Breakout Rooms

1. Japanese
2. Indonesian
3. English
4. Korean
5. Vietnamese
6. CA Catalyst School

## Additional Links and resources

- [Townhall#5 Fund6 Youtube Meeting](https://www.youtube.com/watch?v=0674oS_glAE)
- [Townhall#5 Fund6 Slides](https://docs.google.com/presentation/d/1yfbQQfynQ6jz4U1wpluUucpkjECuPNoMUkYLY32foCQ/edit#slide=id.gb756fa1b15_0_0)

## Eastern Town Hall Social Media Links
 
- Zoom: https://tinyurl.com/Eastern-Townhall-Zoom
- Telegram: https://t.me/joinchat/ODKTOvGnrHEwNTc6
- Discord: https://discord.gg/6T825EyvrG
- Email: eastern.townhall@gmail.com

## Town Hall Social Media Links

**Recurring Registration link**: https://bit.ly/3rCicSR add to your calendars and just simply join each week using the same access.

**Fund6 Challenges Overview**: https://www.youtube.com/watch?v=crs3lVaGejY&t=1821s

**Fund4+5 Feedback Form**: https://forms.gle/CGLwyskXr5Zusdp97  

**Use Discord**

Pitch-Devs Channel https://discord.gg/eJySdx9n6r or use:
@dev-for-hire to ping developers
@designer-for-hire to ping designers

Official proposer guide: https://bit.ly/3AX2sxf 
Proposer guide by Anthony

Proposer TG channel: https://t.me/catalystproposers

Community web 1: https://projectcatalyst.org/resources/proposer 

Community web 2: https://cardanocataly.st/proposers/  

CA Guide (to know how proposals are evaluated in Fund5): https://bit.ly/3iTfWns

Read the guidelines: https://docs.google.com/document/d/1oE_cnP0gksdAanXV4w5DYaDNp_tbYEvyHhTUG4HYZ3Q/edit 

Submit your proposal: http://cardano.ideascale.com/ 

Catalyst announcement channel: https://t.me/cardanocatalyst 

Catalyst Proposers channel on telegram: https://t.me/catalystproposers

**Comment by stephen-rowan** [comment]
## Rough Notes
80 to 83 Participants in main room

**Comment by Mietran0407** [comment]
Today's Vietnam town hall had 30 people coming. There are a lot of newcomers, we decided to spend the first 15 minutes of every town hall to introduce again what is Catalyst and how it works. Today we invited Aidan Rankin- Williams from Playermint to share his journey with Catalyst. Hope to get more people if the meeting moves to Saturday! Wish everyone good night!
