### ISSUE TITLE
Eastern Hemisphere Meeting - Saturday 4th September 08:00 UTC

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#48]
## Eastern Hemisphere Meeting - Saturday 4th September 08:00 UTC

![2021-09-04 (1)](https://user-images.githubusercontent.com/25156451/132089299-cf069b6f-e506-42e3-bd6f-7ab2492b8f31.png)

ETH Proposal Workshop Meeting. Our objective is to lock in additional details on the proposals and refine the budgets for the proposals need them. **We need to update the KPIs, Roadmap, and Budgets.**

- **[Meeting Link](https://us02web.zoom.us/j/84374449716?pwd=emNHcXpHYWIzM3h5dW1NS3dnaFFSdz09)** 

- Last Meeting - #44  
- Next Meeting - #47 

- Last Proposal Workshop - #45 

###  Proposed Attendees

- Yan Tirta (@YanTirta)
- Tim O'Brien (@tuvalusoftware)
- Robert O'Brien (@wolstaeb)
- Felix Weber (@FelixfromSwarm)
- Sermon Blub (@Seomon4u)
- Stephen Whitenstall (@stephen-rowan)
- Steve Lockhard
- Yuta Yuta
- Greg Bell (@grebel-au)
- Andy (@zicozibu)

### Agenda

1. Review the [Grow East Asia Challenge](https://hackmd.io/@c3eth-team/H1Nb8BAgt/edit) Proposal
2. Refine Budgets and KPIs for the remaining proposals
3. Review any Video Scripts. 

Please see meeting notes for #42, #43 and #45 for more details. This is a meeting is an opportunity to review and edit drafts of the proposals' *detailed plan* section for the proposals. We need to finish the proposals this weekend to give us enough time to do translations. 

### Proposal Videos

If we want videos for the proposals please draft a 1min script (approx. 130 English words). The format will be a simple explanation of the proposal by the primary proposer in their language. 

Please either write the script in English or translate it into English, to make it easier to translate and edit. Subtitles will be added. It can be done in a Q&A format. 

We can record it over Zoom, or if you want record it independently. DO NOT worry about editing the material, do any many takes as you need. Jack can edit it all.

#### Draft Scripts

@Mietran0407 has posted her [draft](https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/45#issuecomment-912435903) for the [Distributed Decision Making](https://hackmd.io/@c3eth-team/ry8XMgGbF/edit) proposal.

### Budgets and KPIs

The need to be worked on ASAP. Please have a go at them before the meeting.

**BUDGET:** [C3ETH Proposal(s) Budget Spreadsheet](https://docs.google.com/spreadsheets/d/1BeMc7BW9NFVSWPomM3j4Iv5I7Eveb24P-dFhFOUrCvo/edit?usp=sharing)

The fund amount for [Grow East Asia, Grow Cardano](https://hackmd.io/@c3eth-team/H1Nb8BAgt/edit) is $100K USD. The treasury fund for [Value Onboarding](https://hackmd.io/@c3eth-team/HJ_vUxf-K/edit) is $10K USD. Budgets for the other proposals need to be worked on:

- [Multilingual Challenge](https://hackmd.io/@c3eth-team/B1pIyxfWt/edit) 
- [Distributed Decision Making](https://hackmd.io/@c3eth-team/ry8XMgGbF/edit)
- [Proposer Outreach](https://hackmd.io/@c3eth-team/SJD6SlzZK/edit) 

Brief notes from #32 Proposal budgets need to consider.

- Roles and required Budget for each role.
- Commitments
- Website
- Marketing
- Content creation

**Comment by stephen-rowan** [comment]
## Rough Notes

### Vietnamese Breakout Room
- Duc tiger connected with Steve and IOHK -  My
- We are going to do more marketing campaign - to target universities - My
- Nguyen is our new moderator - Nguyen 
- Experience of blockchain since 2018, It professional - Nguyen
