### ISSUE TITLE
Eastern Hemisphere Townhall Meeting#8 - Saturday 18th September 09:00AM UTC #47

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#49]
![2021-09-18 (1)](https://user-images.githubusercontent.com/25156451/133883385-a8ee42e8-bacb-44f6-96a2-b51a279093b4.png)

- Last Meeting: #47 
- Next Meeting: 

**[Meeting Registration](https://www.meetup.com/Catalyst-Swarm-Sessions/events/qrlmpsyccmbxb/)**

## Meeting Soundbite

[**TO BE DONE**]: fill out after the meeting. Please see [Breakout Room Summaries below](#breakout-room-summaries)

## Attendees

EHT # | Date | Registrations | Participants | Japan | Indonesia | Vietnam | English | Korean | Catalyst School
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
EHT #1 | 29/07/2021 | 86 | 47 | 15 | 14 | 5 | 7 | - |  
EHT #2 | 05/08/2021 |   | 64 | 11 | 11 | 32 | 12 | - |  
EHT #3 | 12/08/2021 | 335 | 93 | 43 | 10 | 29 | 11 | - |  
EHT #4 | 19/08/2021 |   | 94 | 49 | 3 | 19 | 11 | - | 12
EHT #5 | 26/08/2021 |   | 62 | 35 | 7 | 10 | 10 | - | -
EHT #6 | 02/09/2021 |   | 76 | 31 | 6 | 22 | 14 | - | 3
EHT #7 | 09/09/2021 |   | 95 | 39 | 9 | 30 | 7 | 4 | 6
EHT #8 | 18/09/2021 |   |  |  | |  |  |  | 

## Hosts

Hosts, please arrive 30mins before the start of the Townhall to make last-minute adjustments to the schedule and go over the run sheet.

- Yan Tirta (@YanTirta)  - INA 
- Tim O'Brien (@tuvalusoftware )- VN
- Tien Nguyen Anh - VN
- Mie Tran (@Mietran0407) - VN
- Yuta Yuta - JP - Japan
- Robert O'Brien  (@wolstaeb) - EN 
- Felix Weber (@FelixfromSwarm) - EN 
- Andreas Sosilo - IN
- Paul Ko (@haskellcoding29) - KO

### Indonesian

[**TO BE DONE**]: fill out after the meeting. 
### Japan

[**TO BE DONE**]: fill out after the meeting. 
### Vietnam

[**TO BE DONE**]: fill out after the meeting. 
### Korea

[**TO BE DONE**]: fill out after the meeting. 
### English

[**TO BE DONE**]: fill out after the meeting. 

## Run sheet

1. Open room and welcome people.
2. Welcome Slides (MC Mie/Yan)
3. Weclome to the experiment in the respective languages.
4. Ideafeast Eastern Townhall
4. Go to Breakout Rooms (Play Video Guide on loop)

## Breakout Rooms

1. Japanese
2. Indonesian
3. English
4. Korean
5. Vietnamese

## Additional Links and resources

- [Townhall#6 Fund6 Youtube Meeting](https://www.youtube.com/watch?v=sLisPIgHkLM)
- [Townhall#6 Fund6 Slides](https://docs.google.com/presentation/d/1_BGhCFyPgpzoHmx_wuHcskOWDAQYU9pcVu0XXYCV6g4/edit)

## Eastern Town Hall Social Media Links
 
- Zoom: https://tinyurl.com/Eastern-Townhall-Zoom
- Telegram: https://t.me/joinchat/ODKTOvGnrHEwNTc6
- Discord: https://discord.gg/6T825EyvrG
- Email: eastern.townhall@gmail.com

## Town Hall Social Media Links

**Recurring Registration link**: https://bit.ly/3rCicSR add to your calendars and just simply join each week using the same access.

**Fund6 Challenges Overview**: https://www.youtube.com/watch?v=crs3lVaGejY&t=1821s

**Fund4+5 Feedback Form**: https://forms.gle/CGLwyskXr5Zusdp97  

**Use Discord**

Pitch-Devs Channel https://discord.gg/eJySdx9n6r or use:
@dev-for-hire to ping developers
@designer-for-hire to ping designers

Official proposer guide: https://bit.ly/3AX2sxf 
Proposer guide by Anthony

Proposer TG channel: https://t.me/catalystproposers

Community web 1: https://projectcatalyst.org/resources/proposer 

Community web 2: https://cardanocataly.st/proposers/  

CA Guide (to know how proposals are evaluated in Fund5): https://bit.ly/3iTfWns

Read the guidelines: https://docs.google.com/document/d/1oE_cnP0gksdAanXV4w5DYaDNp_tbYEvyHhTUG4HYZ3Q/edit 

Submit your proposal: http://cardano.ideascale.com/ 

Catalyst announcement channel: https://t.me/cardanocatalyst 

Catalyst Proposers channel on telegram: https://t.me/catalystproposers

**Comment by Mietran0407** [comment]
In the #8 ETH, There was 1 point we reached 26 people in the breakout room. We invited Long Nguyen, a co-founder of Minswap, he successfully received approval from fund4 and Minswap is currently a talk in the town, it was an engaging meeting with a lot of questions and curiosity. We will continue to post more attractive content to appeal more people to the ETH.
