### ISSUE TITLE
Eastern Hemisphere Meeting - Monday, 20th September 2021, 0800 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination#51]
### Eastern Hemisphere Meeting - Monday, 20th September 2021, 0800 UTC
- Last Co-ordination Meeting - https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/48
- Next Co-ordination Meeting - 
- 
![2021-09-20](https://user-images.githubusercontent.com/25156451/133980490-82414080-dc02-49fd-ae22-47a0dcb74d50.png)

### Attendees
- Andreas Sosilo - INA - Indonesia 
- Mie Tran  - VN - Vietnam
- Duc Tiger - Vietnam
- Tien Nguyen Anh - VN
- Robert O'Brien - EN 
- Yan Tirta - INA - Indonesia 
- Tim O'Brien - VN - Vietnam
- Yuta Yuta - JP - Japan
- Felix Weber - EN 
- Stephen Whitenstall - EN

### Apologies

- Greg Bell  - EN 
- Seomon Blub - EN

**Comment by stephen-rowan** [comment]
###  Rough Notes

#### Introductions
- Andreas Sosilo - INA - Indonesia
- Duc Tiger - Vietnam

**Comment by stephen-rowan** [comment]
## Translate Invite

Hey to all Fund 6 Proposers!

If you want to reserve a slot for Idea Fest Fund 6, sign up and be ready to present your proposal or challenge in your own language to the world.

DATE: October 2nd, 2021
LOCATION: Zoom
HOST:Eastern Town Hall Team, Catalyst Swarm 

General Information:

- Max. 5 minute pitch + 10 minute Q&A
- We ask each proposer to present only one proposal

>>> More details of the event will be published soon. <<<

Full Name

Email

Link to your Ideascale proposal

In which challenge is your proposal submitted?

**Comment by FelixfromSwarm** [comment]
in attendess there is Daniel Ribar listed..
Dont think that he is part of this project^^

**Comment by stephen-rowan** [comment]
> 
> 
> in attendess there is Daniel Ribar listed..
> Dont think that he is part of this project^^

Taken off - was in old template

**Comment by Mietran0407** [comment]
My translation for the Invite

**Thư mời tham dự**

Xin chào các thành viên có đề xuất dự án cho Fund6!!!

Nếu các bạn muốn giữ 1 chỗ trong Idea Fest Fund6, hãy đăng kí và sẵn sàng chia sẻ dự án hoặc thử thách của bạn với thế giới  bằng chính ngôn ngữ của bạn.

Ngày: 02/10/2021
Địa điểm: Zoom
Chủ trì bởi: Eastern Townhall Team, Catalyst Swarm

Thông tin chung:
Trình bày tối đa: 5 phút + 10 phút hỏi và đáp
Mỗi người đề xuất chỉ được trình bày một dự án.
Nếu có nhiều hơn 1 dự án bạn có thể nhờ đồng đội trình bày.

Thông tin thêm về sự kiện sẽ được thônng báo sớm.
 
Đăng kí dưới mẫu sau:

- Họ và Tên:

- Email:

- Link tới dự án trên Ideascale:

- Dự án của bạn nằm trên hạng mục thách thức nào?

**Comment by FelixfromSwarm** [comment]
All translations done

@YanTirta - Indonesia
@cardanoz - Japanese
@Mietran0407 - Vietnamese

https://docs.google.com/document/d/1mpQrjgHnynOylJZTcYFUwweCM3h6X-0b_fQ6jDL-Py4/edit

**Comment by FelixfromSwarm** [comment]
ah, @wolstaeb or @stephen-rowan .. can you add Andreas to the group here?
Here his git handle: https://github.com/andreassosilo

**Comment by stephen-rowan** [comment]
> 
> 
> ah, @wolstaeb or @stephen-rowan .. can you add Andreas to the group here?
> Here his git handle: https://github.com/andreassosilo

Invite sent for member access to GitHub organization.

S
